-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 14:16:21 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idclient` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `active` ENUM('Y', 'N') NULL DEFAULT 'N',
  `token` VARCHAR(45) NULL,
  `sex` ENUM('W', 'M') NULL,
  `password` VARCHAR(45) NOT NULL,
  `admin` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ad` (
  `idad` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('rent', 'sell') NULL,
  `title` VARCHAR(45) NULL,
  `fee` INT NULL,
  `adress` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `space` FLOAT NULL,
  `furnished` TINYINT(1) NULL,
  `active` TINYINT(1) NULL,
  `addDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  `room` INT NULL,
  `gallery` VARCHAR(45) NULL,
  `client_idclient` INT NOT NULL,
  `content` VARCHAR(255) NULL,
  `property` ENUM('room', 'flat') NULL,
  PRIMARY KEY (`idad`),
  INDEX `fk_ad_client_idx` (`client_idclient` ASC),
  CONSTRAINT `fk_ad_client`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `mydb`.`user` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `fromUser` VARCHAR(45) NULL,
  `toUser` VARCHAR(45) NULL,
  `tittle` VARCHAR(45) NULL,
  `content` VARCHAR(255) NULL,
  `sendDate` DATETIME NULL,
  PRIMARY KEY (`idmessage`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
