package com.example.yoursquare.dao;

import java.sql.Connection;
import java.sql.SQLException;

import com.example.yoursquare.dao.mappers.*;
import com.example.yoursquare.dao.uow.IUnitOfWork;
import com.example.yoursquare.model.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;

public class AdRepository extends RepositoryBase<Ad> implements IAdRepository {


	public AdRepository(Connection connection,
			IMapResultSetIntoEntity<Ad> mapper,
			IAdRepository IAdRepository, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}
	
	@Override
	protected String tableName() {
		return "ad";
	}
	
	protected String createTableSql() {
		return "CREATE TABLE ad("
					+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
					+ "id INT,"
					+ "title VARCHAR(20),"
					+ "fee INT,"
					+ "adress VARCHAR(20),"
					+ "city VARCHAR(20),"
					+ "zipcode VARCHAR(20),"
					+ "space float,"
					+ "furnished BOOLEAN,"
					+ "active BOOLEAN,"
					+ "addDate DATE,"
					+ "endDate DATE,"
					+ "room INT,"
					+ "gallery VARCHAR(20),"
					+ "content VARCHAR(20),"
					+ "type ENUM(SELL,RENT),"
					+ "property ENUM(FLAT,ROOM),"
					+ ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO ad(title,fee,adress,city,zipcode,space,furnished,active,addDate,endDate,room,gallery,content,type,property) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE ad set title=?, fee=?, adress=?, city=?, zipcode=?, space=?, furnished=?, active=?, addDate=?, endDate=?, room=?, gallery=?, content=?, type=?, property=? WHERE id=?";
	}


	@Override
	protected void setupInsert(Ad entity) throws SQLException {
		insert.setString(1, entity.getTitle());
		insert.setInt(2, entity.getFee());
		insert.setString(3, entity.getAdress());
		insert.setString(4, entity.getCity());
		insert.setString(5, entity.getZipcode());
		insert.setFloat(6, entity.getSpace());
		insert.setBoolean(7, entity.isFurnished());
		insert.setBoolean(8, entity.isActive());
		insert.setDate(9, entity.getAddDate());
		insert.setDate(10, entity.getEndDate());
		insert.setInt(11, entity.getRoom());
		insert.setString(12, entity.getGallery());
		insert.setString(13, entity.getContent());
		//insert.Enum(14, entity.type);
		//insert.setEnum(rs.getEnum("property"));
		
	}

	@Override
	protected void setupUpdate(Ad entity) throws SQLException {
		update.setString(1, entity.getTitle());
		update.setInt(2, entity.getFee());
		update.setString(3, entity.getAdress());
		update.setString(4, entity.getCity());
		update.setString(5, entity.getZipcode());
		update.setFloat(6, entity.getSpace());
		update.setBoolean(7, entity.isFurnished());
		update.setBoolean(8, entity.isActive());
		update.setDate(9, entity.getAddDate());
		update.setDate(10, entity.getEndDate());
		update.setInt(11, entity.getRoom());
		update.setString(12, entity.getGallery());
		update.setString(13, entity.getContent());
		//update.Enum(14, entity.type);
		//update.setEnum(rs.getEnum("property"));
		
}

	public List<Ad> byUser(User user) {
		// TODO Auto-generated method stub
		return null;
	}

}
