package com.example.yoursquare.dao;
 
import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;

import com.example.yoursquare.dao.mappers.IMapResultSetIntoEntity;
import com.example.yoursquare.dao.uow.IUnitOfWork;
import com.example.yoursquare.model.Message;
import com.example.yoursquare.model.User;

    public class MessageRepository extends RepositoryBase<Message> implements IMessageRepository {
 
 
    	public MessageRepository(Connection connection,
    			IMapResultSetIntoEntity<Message> mapper,
    			IUnitOfWork uow) {
    		super(connection, mapper, uow);
    	}
        
    	@Override
    	protected String tableName() {
    		return "message";
    	}
 
        protected String createTableSql() {
        		return "CREATE TABLE message("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY,"
                + "fromUser INT,"
                + "toUser INT,"
                + "title VARCHAR(20),"
                + "content VARCHAR(20),"
                + "sendDate DATE,"
				+ "FOREIGN KEY (fromUser) REFERENCES user (id),"
				+ "FOREIGN KEY (toUser) REFERENCES user (id),"
				+ ")";
        }
        
        @Override
    	protected String insertSql() {
    		return "INSERT INTO user(message,fromUser,toUser,title,content,sendDate) VALUES(?,?,?,?)";
    	}
        
    	@Override
    	protected String updateSql() {
    		return "UPDATE user set message=?, fromUser=?, toUser=?, title=?, content=?, sendDate=? WHERE id=?";
    	}

        protected void setupInsert(Message entity) throws SQLException {
                insert.setInt(1, entity.getFromUser());
                insert.setInt(2, entity.getToUser());
                insert.setString(3, entity.getTitle());
                insert.setString(4, entity.getContent());
			    insert.setDate(5, entity.getSendDate());
		}
 
        protected void setupUpdate(Message entity) throws SQLException {
            	update.setInt(1, entity.getFromUser());
                update.setInt(2, entity.getToUser());
                update.setString(3, entity.getTitle());
                update.setString(4, entity.getContent());
				update.setDate(5, entity.getSendDate());
        }

		public java.util.List<Message> byUser(User user) {
			// TODO Auto-generated method stub
			return null;
		}
    }